### PR TITLE
add a method: CallParmsObj

### PR DESCRIPTION
**Pull request by twmsh**
add a method CallParamsObj to pass a struct object, not a array/slice

### CODE REVIEW

**Comment by ybbus** [comment]
What happens if you call:
client.CallParmsObj("myMethod",2)

This is not a valid jsonrpc call.

**Comment by twmsh** [comment]
I want to pass a obj/struct  as params, like this 
{
    "jsonrpc": "2.0", 
    "method": "getapp", 
    "params": {
        "appkey": "11ee74b5-facd-4a8a-bcfe-8a512a85a601", 
        "id": "b36a601c-c64c-465e-b125-3be4eaaf4106"
    }, 
    "id": 2
}

type GetAppReq struct {
    Appkey string `json:"appkey"`
    Id     string `json:"id"`
}
req := new(GetAppReq)
res, err := client.CallParmsObj("getapp", *req)

so  need a method like CallParmsObj
@ybbus

**Comment by ybbus** [comment]
Yes, I did unterstand. But what should we do with the case that you can generate invalid json rpc requests by calling for example:
client.CallParmsObj("getapp", 2)

If we want to return an error e.g. InvalidParam, your function should check if the param is really a struct and not something else (e.g. int, string, etc...)

**Comment by ybbus** [comment]
Of course we could just return the error response of the rpc server but I don't know if we should allow the client user to generate invalid requests regarding the json rpc spec.

**Comment by ybbus** [comment]
I will take a close look at reflections of go, maybe we can handle the error case and check if parameter is a struct or pointer of struct

**Pull request closed without merging**
